/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampsRouteImport } from './routes/camps'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as MissingRouteImport } from './routes/missing'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as ApiPublicWarimitraRouteImport } from './routes/api/public/warimitra'
import { Route as ApiPublicExotelHospitalTransferRouteImport } from './routes/api/public/exotel/hospital-transfer'
import { Route as ApiPublicExotelVoicebotRouteImport } from './routes/api/public/exotel/voicebot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsRoute = CampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingRoute = MissingRouteImport.update({
  id: '/missing',
  path: '/missing',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWarimitraRoute = ApiPublicWarimitraRouteImport.update({
  id: '/api/public/warimitra',
  path: '/api/public/warimitra',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExotelHospitalTransferRoute =
  ApiPublicExotelHospitalTransferRouteImport.update({
    id: '/api/public/exotel/hospital-transfer',
    path: '/api/public/exotel/hospital-transfer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExotelVoicebotRoute = ApiPublicExotelVoicebotRouteImport.update({
  id: '/api/public/exotel/voicebot',
  path: '/api/public/exotel/voicebot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/command': typeof CommandRoute
  '/community': typeof CommunityRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/missing': typeof MissingRoute
  '/voice': typeof VoiceRoute
  '/api/public/warimitra': typeof ApiPublicWarimitraRoute
  '/api/public/exotel/hospital-transfer': typeof ApiPublicExotelHospitalTransferRoute
  '/api/public/exotel/voicebot': typeof ApiPublicExotelVoicebotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/command': typeof CommandRoute
  '/community': typeof CommunityRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/missing': typeof MissingRoute
  '/voice': typeof VoiceRoute
  '/api/public/warimitra': typeof ApiPublicWarimitraRoute
  '/api/public/exotel/hospital-transfer': typeof ApiPublicExotelHospitalTransferRoute
  '/api/public/exotel/voicebot': typeof ApiPublicExotelVoicebotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camps': typeof CampsRoute
  '/command': typeof CommandRoute
  '/community': typeof CommunityRoute
  '/emergency': typeof EmergencyRoute
  '/facilities': typeof FacilitiesRoute
  '/missing': typeof MissingRoute
  '/voice': typeof VoiceRoute
  '/api/public/warimitra': typeof ApiPublicWarimitraRoute
  '/api/public/exotel/hospital-transfer': typeof ApiPublicExotelHospitalTransferRoute
  '/api/public/exotel/voicebot': typeof ApiPublicExotelVoicebotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camps'
    | '/command'
    | '/community'
    | '/emergency'
    | '/facilities'
    | '/missing'
    | '/voice'
    | '/api/public/warimitra'
    | '/api/public/exotel/hospital-transfer'
    | '/api/public/exotel/voicebot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camps'
    | '/command'
    | '/community'
    | '/emergency'
    | '/facilities'
    | '/missing'
    | '/voice'
    | '/api/public/warimitra'
    | '/api/public/exotel/hospital-transfer'
    | '/api/public/exotel/voicebot'
  id:
    | '__root__'
    | '/'
    | '/camps'
    | '/command'
    | '/community'
    | '/emergency'
    | '/facilities'
    | '/missing'
    | '/voice'
    | '/api/public/warimitra'
    | '/api/public/exotel/hospital-transfer'
    | '/api/public/exotel/voicebot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampsRoute: typeof CampsRoute
  CommandRoute: typeof CommandRoute
  CommunityRoute: typeof CommunityRoute
  EmergencyRoute: typeof EmergencyRoute
  FacilitiesRoute: typeof FacilitiesRoute
  MissingRoute: typeof MissingRoute
  VoiceRoute: typeof VoiceRoute
  ApiPublicWarimitraRoute: typeof ApiPublicWarimitraRoute
  ApiPublicExotelHospitalTransferRoute: typeof ApiPublicExotelHospitalTransferRoute
  ApiPublicExotelVoicebotRoute: typeof ApiPublicExotelVoicebotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps': {
      id: '/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof CampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing': {
      id: '/missing'
      path: '/missing'
      fullPath: '/missing'
      preLoaderRoute: typeof MissingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/warimitra': {
      id: '/api/public/warimitra'
      path: '/api/public/warimitra'
      fullPath: '/api/public/warimitra'
      preLoaderRoute: typeof ApiPublicWarimitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exotel/hospital-transfer': {
      id: '/api/public/exotel/hospital-transfer'
      path: '/api/public/exotel/hospital-transfer'
      fullPath: '/api/public/exotel/hospital-transfer'
      preLoaderRoute: typeof ApiPublicExotelHospitalTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/exotel/voicebot': {
      id: '/api/public/exotel/voicebot'
      path: '/api/public/exotel/voicebot'
      fullPath: '/api/public/exotel/voicebot'
      preLoaderRoute: typeof ApiPublicExotelVoicebotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampsRoute: CampsRoute,
  CommandRoute: CommandRoute,
  CommunityRoute: CommunityRoute,
  EmergencyRoute: EmergencyRoute,
  FacilitiesRoute: FacilitiesRoute,
  MissingRoute: MissingRoute,
  VoiceRoute: VoiceRoute,
  ApiPublicWarimitraRoute: ApiPublicWarimitraRoute,
  ApiPublicExotelHospitalTransferRoute: ApiPublicExotelHospitalTransferRoute,
  ApiPublicExotelVoicebotRoute: ApiPublicExotelVoicebotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
